version: "3.9"
    
services:
  # mariaDB
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: example.com # set to fqdn of host
    ports:
      - 19999:19999
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    environment:
      - NETDATA_CLAIM_TOKEN=-mOc_4WTXHiVEI35mAD_Y_542pvU88N7e3i14Jb5WgiP3aArDxBTb9Wd7Kg7kEYb80JvtPnWLNvByr6Rk61KQCVeGmIrqA6VwiGlWYDiQoNz2OyET2AmxKIF7i4CqtBDqtcxYtM
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
      - NETDATA_CLAIM_ROOMS=399289e1-adfa-4233-a02e-e5b75044d1d4
  db:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

# phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    links:
      - db:db
    
  wordpress:
    depends_on:
      - db
    image: wordpress:php8.1
    volumes:
      - wordpress_data:/var/www/html
      - ./config:/etc/php5/apache2/conf.d/custom.php.ini
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WP_REDIS_HOST: redis
      WP_CACHE_KEY_SALT: wp-docker-5DknvYepdjyJMo8gDqrLhrpAJUQ
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_CONFIG_EXTRA: >
          define( 'WP_REDIS_HOST', 'redis' );
          define( 'WP_CACHE_KEY_SALT', 'wp-docker-5DknvYepdjyJMo8gDqrLhrpAJUQ' );
  wpcli:
      image: wordpress:cli
      volumes:
      - wordpress_data:/var/www/html
      - ./config:/etc/php5/apache2/conf.d/custom.php.ini
      environment:
        WORDPRESS_DB_HOST: db
        WORDPRESS_DB_NAME: wordpress
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_PASSWORD: wordpress
      depends_on:
        - db
        - wordpress

  mailcatcher:
    image: chatwork/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
        - "6379:6379"

volumes:
  db_data: {}
  wordpress_data: {}
  netdataconfig:
  netdatalib:
  netdatacache: