version: "3.9"
    
services:
  # mariaDB
  db:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

# phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    links:
      - db:db
    
  wordpress:
    depends_on:
      - db
    image: wordpress:php8.1
    volumes:
      - wordpress_data:/var/www/html
      - ./config:/etc/php5/apache2/conf.d/custom.php.ini
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WP_REDIS_HOST: redis
      WP_CACHE_KEY_SALT: wp-docker-5DknvYepdjyJMo8gDqrLhrpAJUQ
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_CONFIG_EXTRA: >
          define( 'WP_REDIS_HOST', 'redis' );
          define( 'WP_CACHE_KEY_SALT', 'wp-docker-5DknvYepdjyJMo8gDqrLhrpAJUQ' );

  mailcatcher:
    image: chatwork/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
        - "6379:6379"

volumes:
  db_data: {}
  wordpress_data: {}